[package]
name = "blackjack_rust"
version = "0.1.1"
authors = ["David Garcia <davidgmorillop@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.6"